const agents = [
  {
    id: "8",
    city_id: "8",
    district_id: null,
    parish_id: null,
    code: "agent-saudi-arabia-8",
    owner: "Owner of 8",
    name: "Agent 8",
    address: "Mecca - 300 Amherst StNashua, NH",
    lat: "21.4362544",
    lng: "39.6817338",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-saudi-arabia-8.png",
    distance: "0",
    schedules: [
      {
        id: "50",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "51",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "52",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "53",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "54",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "55",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "56",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "",
    is_center: "1",
  },
  {
    id: "7",
    city_id: "7",
    district_id: null,
    parish_id: null,
    code: "agent-saudi-arabia-7",
    owner: "Owner of 7",
    name: "Agent 7",
    address: "Ta'if - 300 Amherst StNashua, NH",
    lat: "21.3861583",
    lng: "40.2462699",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-saudi-arabia-7.png",
    distance: "0",
    schedules: [
      {
        id: "43",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "44",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "45",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "46",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "47",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "48",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "49",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "",
    is_center: "1",
  },
  {
    id: "6",
    city_id: "6",
    district_id: null,
    parish_id: null,
    code: "agent-england-6",
    owner: "Owner of 6",
    name: "Agent 6",
    address: "Darlington - 300 Amherst StNashua, NH",
    lat: "54.5312376",
    lng: "-1.5945478",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-england-6.png",
    distance: "0",
    schedules: [
      {
        id: "36",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "37",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "38",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "39",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "40",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "41",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "42",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "1",
    is_center: "1",
  },
  {
    id: "5",
    city_id: "5",
    district_id: null,
    parish_id: null,
    code: "agent-england-5",
    owner: "Owner of 5",
    name: "Agent 5",
    address: "Newcastle - 300 Amherst StNashua, NH",
    lat: "54.2130465",
    lng: "-5.9371697",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-england-5.png",
    distance: "0",
    schedules: [
      {
        id: "29",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "30",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "31",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "32",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "33",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "34",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "35",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "1",
    is_center: "1",
  },
  {
    id: "4",
    city_id: "4",
    district_id: null,
    parish_id: null,
    code: "agent-russia-4",
    owner: "Owner of 4",
    name: "Agent 4",
    address: "Bely Anuy - 300 Amherst StNashua, NH",
    lat: "51.2313653",
    lng: "84.8905916",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-russia-4.png",
    distance: "0",
    schedules: [
      {
        id: "22",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "23",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "24",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "25",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "26",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "27",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "28",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "",
    is_center: "1",
  },
  {
    id: "3",
    city_id: "3",
    district_id: null,
    parish_id: null,
    code: "agent-russia-3",
    owner: "Owner of 3",
    name: "Agent 3",
    address: "Gorno-Altaysk - 300 Amherst StNashua, NH",
    lat: "51.9453556",
    lng: "85.9028746",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-russia-3.png",
    distance: "0",
    schedules: [
      {
        id: "15",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "16",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "17",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "18",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "19",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "20",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "21",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "",
    is_center: "1",
  },
  {
    id: "2",
    city_id: "2",
    district_id: null,
    parish_id: null,
    code: "agent-russia-2",
    owner: "Owner of 2",
    name: "Agent 2",
    address: "Adygeysk - 300 Amherst StNashua, NH",
    lat: "44.8839711",
    lng: "39.1701864",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-russia-2.png",
    distance: "0",
    schedules: [
      {
        id: "8",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "9",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "10",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "11",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "12",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "13",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "14",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "",
    is_center: "1",
  },
  {
    id: "1",
    city_id: "1",
    district_id: null,
    parish_id: null,
    code: "agent-russia-1",
    owner: "Owner of 1",
    name: "Agent 1",
    address: "Maykop - 300 Amherst StNashua, NH",
    lat: "44.6051742",
    lng: "39.9456508",
    zipcode: "03063",
    phones: null,
    url: null,
    path: "uploads/seeder/agent-russia-1.png",
    distance: "0",
    schedules: [
      {
        id: "1",
        weekday: "Saturday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "2",
        weekday: "Sunday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "3",
        weekday: "Monday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "4",
        weekday: "Tuesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "5",
        weekday: "Wednesday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "6",
        weekday: "Thursday",
        start: "07:00",
        end: "12:30",
      },
      {
        id: "7",
        weekday: "Friday",
        start: "07:00",
        end: "12:30",
      },
    ],
    is_open: "",
    is_center: "1",
  },
];

export default agents;
